# Generated by Django 5.0.7 on 2024-07-30 03:39

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Имя автора', max_length=50, unique=True, verbose_name='Имя')),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Жанр книги', max_length=50, unique=True, verbose_name='Жанр')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название книги', max_length=150, verbose_name='Название книги')),
                ('year', models.PositiveIntegerField(help_text='год выхода книге', verbose_name='Год выхода книги')),
                ('cover', models.ImageField(upload_to=book.models.user_directory_path)),
                ('author', models.ManyToManyField(help_text='Авторы', related_name='books', to='book.authors', verbose_name='Авторы книги')),
                ('genre', models.ManyToManyField(help_text='Жанры', related_name='books', to='book.genres', verbose_name='Жанры книги')),
            ],
        ),
    ]
